/**
 * Generates shared/config.gen.ts (gitignored) from:
 *   config.local.toml   — private production tuning, gitignored (§21)
 *   config.example.toml — committed example defaults (fallback)
 *
 * Workers and the scoring engine import the generated module, so no weight
 * or threshold is ever hardcoded (PROJECT_PLAN.md §21). Runs on postinstall
 * and before any build/deploy (`npm run config:gen`).
 *
 * This file handles NO secrets — secrets go through `wrangler secret put`.
 */

import { parse } from 'smol-toml';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const localPath = path.join(root, 'config.local.toml');
const examplePath = path.join(root, 'config.example.toml');
const source = existsSync(localPath) ? localPath : examplePath;

const config = parse(readFileSync(source, 'utf8'));

// Minimal shape validation — fail loudly rather than deploy a broken scorer.
const requiredSections = ['bands', 'weights', 'trust_credits', 'detection', 'population', 'blocklist', 'adguard', 'retention'];
for (const s of requiredSections) {
  if (typeof config[s] !== 'object' || config[s] === null) {
    console.error(`gen-config: missing [${s}] section in ${path.basename(source)}`);
    process.exit(1);
  }
}
for (const [k, v] of Object.entries(config.weights)) {
  if (v !== 'hard' && typeof v !== 'number') {
    console.error(`gen-config: [weights] ${k} must be a number or "hard", got ${JSON.stringify(v)}`);
    process.exit(1);
  }
}

const banner = `// AUTO-GENERATED by scripts/gen-config.mjs from ${path.basename(source)} — DO NOT EDIT.
// Gitignored: regenerate with \`npm run config:gen\`. See PROJECT_PLAN.md §21.

/** A signal weight: points added to bot_score, or "hard" (forces score=100). */
export type Weight = number | 'hard';

export interface ScoringConfig {
  bands: { clean_max: number; suspect_max: number };
  weights: Record<string, Weight>;
  trust_credits: Record<string, number>;
  detection: {
    expensive_checks_enabled: boolean;
    expensive_checks_sample: number;
    mobile_sensors_enabled: boolean;
    honeypot_enabled: boolean;
  };
  population: Record<string, number>;
  blocklist: { default_ttl_days: number; hard_signal_permanent: boolean; share_bare_ip: boolean };
  adguard: { default_mode: string; verdict_timeout_ms: number; shadow_days: number };
  retention: { raw_events_days: number };
}

export const CONFIG: ScoringConfig = `;

writeFileSync(path.join(root, 'shared', 'config.gen.ts'), banner + JSON.stringify(config, null, 2) + ';\n');
console.log(`gen-config: shared/config.gen.ts generated from ${path.basename(source)}`);
